### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by longemen3000**
This PR reduces the amount of dependencies of this package. `TrajectoryGamesBase` was only used for one function, while `Zygote` and `FiniteDiff` was only used for tests.

### CODE REVIEW

**Comment by lassepe** [comment]
I think these are good changes. Zygote and FiniteDiff can be removed entirely. The test directory has its own Project.toml

**Review by dfridovi — APPROVED** [review]

**Comment by dfridovi** [comment]
@longemen3000 looks like tests are failing on this. Once tests pass and @lassepe’s comment is addressed let’s get this merged!

**Comment by dfridovi** [comment]
@longemen3000 i think there’s a dependency still missing in the tests

**Comment by longemen3000** [comment]
There is something wrong in the tests, that maybe is related to removing TrajectoryGamesBase.jl. I need to investigate in the meanwhile. I'm gonna close this and create another PR removing only Zygote and FiniteDiff

**Pull request closed without merging**
